# bundle exec jekyll serve
remote_theme: samarsault/plainwhite-jekyll

title: OH_note
url: "https://sdpl-oh.github.io/"
baseurl: ""

author: OH SANG JIN
email: osj5588@pusan.ac.kr
description: > 
  Ship Design & Production Lab.
show_excerpts: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: OH SANG JIN
  tagline: SDPL
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: true
  portfolio_image: "assets/portfolio.jpeg"
  html_lang: "kr" 
  condensed_mobile:
    - home
    - page
    - post
  # generate social links in footer
  social_links:
    twitter: oh_voyage
    github:  SDPL-Oh
    # linkedIn: in/samarsault
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    email: osj5588@pusan.ac.kr

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
